name: Gradle Package Build

on:
#  push:
#    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set Test Version Variable
        id: set_version
        run: |
          echo "release_version=$(grep -oP 'version = \"\K[^\"]+' build.gradle.kts)" >> $GITHUB_ENV

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew buildPlugin

      #      - name: Download artifact
      #        uses: actions/download-artifact@v2
      #        with:
      #          name: build
      #          path: build

      - name: Public Release
        id: create_release
        uses: softprops/action-gh-release@master
        with:
          tag_name: v${{ env.release_version }}_build${{ github.run_number }}
          name: v${{ env.release_version }}
          body: Public Release
          draft: false
          prerelease: false
          files: build/distributions/*.zip
